[package]
name = "hack-emulator"
version = "0.1.0"
authors = ["Roy Brunton <notnurbyor@googlemail.com>"]

[dependencies]
byteorder = "*"

[dependencies.sdl]
git = "https://github.com/brson/rust-sdl.git"
